"""
Password-reset email delivery.

Firebase Auth's built-in `sendPasswordResetEmail()` (client SDK) sends mail
from a shared `<project>.firebaseapp.com` sender with no dedicated domain
reputation — most inbox providers treat that combination (unauthenticated,
shared, high-volume sender + "reset your password" content, a common
phishing pattern) with suspicion, which is why those emails land in Spam.

This module fixes deliverability without touching Firebase's own security
model:

1. The reset *link* is still generated by Firebase Admin SDK
   (`generate_password_reset_link`) — same signed, time-limited, single-use
   action code Firebase would have used anyway. Nothing about the link's
   security properties changes.
2. The *delivery* of that link happens over SendGrid, from a domain the
   caller has completed Sender Authentication (SPF/DKIM) for — see
   `SENDER_EMAIL` in `app/core/config.py`. That domain-level authentication
   is what actually fixes inbox placement; this module cannot do that part,
   it only sends through whatever verified sender is configured.
"""

from __future__ import annotations

import logging
from urllib.parse import parse_qs, quote, urlparse

from firebase_admin import auth as firebase_auth
try:
    from sendgrid import SendGridAPIClient
    from sendgrid.helpers.mail import Mail
    SENDGRID_AVAILABLE = True
except ImportError:
    SendGridAPIClient = None
    Mail = None
    SENDGRID_AVAILABLE = False

from app.core.config import APP_DOMAIN, SENDER_EMAIL, SENDGRID_API_KEY
from app.utils.auth_verifier import get_firebase_app

logger = logging.getLogger("senova.email")


class EmailServiceError(Exception):
    """Raised when link generation or sending fails for a reason the caller
    should know about (e.g. missing configuration). Route handlers catch
    this and still return the generic "if that email exists" response to
    the end user — this exception exists for logging/observability only."""


def _build_reset_link(email: str) -> str:
    """
    Generates Firebase's secure, signed password-reset link via the Admin
    SDK, then rewrites it to point at our own branded confirmation page.

    Why the rewrite: `generate_password_reset_link` returns a link aimed at
    Firebase's hosted action handler
    (`https://<project>.firebaseapp.com/__/auth/action?...&oobCode=...`),
    with our `url` only tacked on as a post-reset `continueUrl`. Following
    that link would show Firebase's own unbranded page — the exact thing
    this flow exists to replace. The `oobCode` is the only part that
    actually matters (it's the signed, single-use, 1-hour token), so we lift
    it out and hand it to our own page, which redeems it client-side via
    `verifyPasswordResetCode` / `confirmPasswordReset`.

    Doing it this way needs no Firebase Console configuration — the
    alternative is setting a project-wide "custom action URL" in the
    console, which would also silently change the email-verification flow.

    Raises `firebase_auth.UserNotFoundError` if no account exists for this
    email — callers must catch this and still return the generic success
    message, never let it reach the HTTP response.
    """
    action_code_settings = firebase_auth.ActionCodeSettings(
        url=f"{APP_DOMAIN}/reset-password-confirm",
        handle_code_in_app=True,
    )
    app = get_firebase_app()
    firebase_link = firebase_auth.generate_password_reset_link(
        email, action_code_settings, app=app
    )

    oob_code = parse_qs(urlparse(firebase_link).query).get("oobCode", [None])[0]
    if not oob_code:
        # Firebase changed its link shape — better to fail loudly (and fall
        # back to the raw Firebase link) than to email a broken URL.
        logger.error("Could not extract oobCode from the generated reset link.")
        return firebase_link

    return f"{APP_DOMAIN}/reset-password-confirm?oobCode={quote(oob_code, safe='')}"


def _send_via_sendgrid(to_email: str, reset_link: str) -> None:
    if not SENDGRID_AVAILABLE:
        raise EmailServiceError(
            "SendGrid package is not installed — cannot send password reset email."
        )
    if not SENDGRID_API_KEY:
        raise EmailServiceError(
            "SENDGRID_API_KEY is not configured — cannot send password reset email."
        )

    message = Mail(
        from_email=SENDER_EMAIL,
        to_emails=to_email,
        subject="Reset your SENOVA Dashboard password",
        html_content=f"""
            <p>Hello,</p>
            <p>We received a request to reset your SENOVA Dashboard password.
            Click the link below to choose a new one:</p>
            <p><a href="{reset_link}">Reset your password</a></p>
            <p>This link expires in 1 hour and can only be used once. If you
            didn't request this, you can safely ignore this email — your
            password will not be changed.</p>
            <p>— SENOVA Digital Lab</p>
        """,
    )
    sg = SendGridAPIClient(SENDGRID_API_KEY)
    response = sg.send(message)
    if response.status_code >= 300:
        raise EmailServiceError(
            f"SendGrid responded with status {response.status_code} sending to {to_email}."
        )


def is_email_delivery_configured() -> bool:
    """
    Whether this deployment can actually deliver a reset email itself.

    Reports server configuration state only — never anything about whether a
    given account exists — so it is safe to surface to an unauthenticated
    caller. The frontend uses it to decide whether to fall back to
    Firebase's own (deliverability-poor but functional) email sender while
    SendGrid domain authentication is still pending.
    """
    return SENDGRID_AVAILABLE and bool(SENDGRID_API_KEY)


def send_password_reset_email(email: str) -> None:
    """
    Generates a Firebase reset link and sends it via SendGrid.

    Deliberately does not distinguish "no such account" from "email sent"
    to its caller in any way that could leak through — it either returns
    normally (email sent) or raises. Route handlers must catch every
    exception from this function and still respond with the generic
    "if that email exists" message; see `app/api/routes/auth.py`.
    """
    reset_link = _build_reset_link(email)
    _send_via_sendgrid(email, reset_link)
    logger.info("Password reset email sent.")
